### ISSUE TITLE
defekter Link in iobroker auf die Dokumentation

### ISSUE THREAD

**Issue by Klaus-Lucas** [iobroker-community-adapters/ioBroker.pvforecast#128]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (used the search)
- [X] This issue is not described in the adapter documentation / FAQ

### API

forecast.solar

### The problem

Im iobroker wird unter Help die deutsche Dokumentation hierüber verlinkt:
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/main/docs/de/README.md
muss aber so heißen:
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/docs/de/README.md

### Version of nodejs

18.19.0

### Version of ioBroker js-controller

5.0.17

### Version of Adapter

2.9.0

**Comment by Klaus-Lucas** [comment]
Ich würde sowas ja durch deepl.com schieben und dann ggf. nacharbeiten.
Aber das ist nicht das Problem. Beide Sprachversionen sind im iobroker falsch verlinkt.
Du bietest hier im Git doch diese 2 funktionierende Links zur Doku an:
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/**blob**/main/docs/de/README.md
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/**blob**/main/docs/en/README.md
Im iobroker aber diese:
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/main/docs/de/README.md
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/main/docs/en/README.md
Warum nimmst du die aus Git nicht auch im iobroker?

**Comment by mcm1957** [comment]
Kann das Problem hier nachstellen. Siehe Link am unteren Rand

![image](https://github.com/iobroker-community-adapters/ioBroker.pvforecast/assets/28575778/f3d3f885-2326-4f6d-b5ca-832535bc122a)

**Comment by mcm1957** [comment]
Im README:ms steht ein relativer Pfad.
```[🇺🇸 Documentation](./docs/en/README.md)```

Entweder muss da ein absoluter Pfad rein oder admin macht was "Komisches"

**Comment by klein0r** [comment]
Fehler gefunden. Liegt am Admin. `master` wird zu `blob/master` ersetzt. Default branch `main` aber nicht zu `blob/main`

**Comment by Klaus-Lucas** [comment]
Top. Danke.

**Comment by mcm1957** [comment]
Im snmp hab ich den Link so definiert:

[english documentation](docs/en/snmp.md)<br>

Das funktioniert.

**Comment by klein0r** [comment]
PR is offen
