### ISSUE TITLE
[Enhancement]: Damping factor for Forecast.solar

### ISSUE THREAD

**Issue by coltc50** [iobroker-community-adapters/ioBroker.pvforecast#130]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Used integration

forecast solar

### The problem

I like to have the damping factor configured because my solar is shadded in the morning. Is there a way to add it?

### Version of nodejs

18.19

### Version of ioBroker js-controller

5.0.17

### Version of adapter

2.9.1

**Comment by coltc50** [comment]
I forked your github and hardcoded my needed damping factor to the script. Installed it from my forked github into iobroker and it works.
Can be closed... but it would be nice if it can adjusted in the settings...

**Comment by klein0r** [comment]
> but it would be nice if it can adjusted in the settings...

Since you are able to understand and modify the code: Please submit a PR

**Comment by coltc50** [comment]
I think I understand the code but I search the index.html for the admin panel to add a new point... I don't find this page in github...

**Comment by mcm1957** [comment]
Adapter uses jsonConfig. The config UI must be adapted at admin/jsonConfig.json

**Comment by coltc50** [comment]
Thanks for help... I added a pull request... Add it quick and dirty to pv tab.

**Comment by coltc50** [comment]
Sorry, had no time to work on it before. See now it's added... Great and thanx for help...

**Comment by mcm1957** [comment]
Well if it's added this issue could be closed? Couldnt it?
