### ISSUE TITLE
no api link in the adapter page

### ISSUE THREAD

**Issue by wschiro** [iobroker-community-adapters/ioBroker.pvforecast#132]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Used integration

forecast.solar

### The problem

in the adapter I can choose the forecast.solar only. In the help is the link to api.forecast.solar
my adapter doesn't work, the error message is:
	2024-01-27 13:57:21.217	error	Axios Error AxiosError: Request failed with status code 404
the api in a browser works properly, but not the adapter
need any help

### iobroker.current.log (in debug mode!)

the error message is the same

### Version of nodejs

16.19.1

### Version of ioBroker js-controller

4.0.24

### Version of adapter

2.9.1

**Comment by klein0r** [comment]
Debug log?

**Comment by wschiro** [comment]
the adapter is in debugstate, there is no difference between debug and info
in the description of the adapter and in the help is to fill out a link, but it isn't in the page

**Comment by wschiro** [comment]
i installed the adapter on another raspi, it works

**Comment by wschiro** [comment]
i installed the adapter on another raspi, it works
