### ISSUE TITLE
[Bug]: Validator issue in the jsonConfig.json

### ISSUE THREAD

**Issue by HGlab01** [iobroker-community-adapters/ioBroker.pvforecast#133]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Used integration

Forcast.solar

### The problem

issue in the jsonConfig.json
pvforecast has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"iconPosition"},"message":"must NOT have additional properties"}]

### Version of nodejs

20.11.0

### Version of ioBroker js-controller

5.0.17

### Version of adapter

2.9.1

**Comment by klein0r** [comment]
See https://github.com/ioBroker/adapter-react-v5/issues/266
