### ISSUE TITLE
[Bug]: updated FC values only considered with instance restart - periodic calls fetch outdated values

### ISSUE THREAD

**Issue by n4pstarr** [iobroker-community-adapters/ioBroker.pvforecast#176]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Used integration

Solcast

### The problem

Hi all,

with changing from Forecast.Solar to Solcast I'm first of all happy with the gain of preciceness of solar FC that Solcast offers.
But I'm suffering from forecast values not being updated.

Attached, you can see that the values showing in the log on 14:00 were updated to the objects already late in the morning (07:26 -I perform and instance restart at dawn as a small workaround already).

The CSV and JSON from toolkit.solcast.com.au contain updated values - different ones from the API call of the adapter.

As soon as I restart the instance, the values visible in the CSV/JSON are fetched and booked to the objects.
By only updating future values and initializing the ones of the past of the current day, this is no suitable option to get a proper daily sum.

Log:
![grafik](https://github.com/user-attachments/assets/804fa6de-e499-46ef-9bd3-6adbb8fadf49)

Objects:
![grafik](https://github.com/user-attachments/assets/448b616b-5a5c-4655-9137-87ebf8eb5628)

CSV:
![grafik](https://github.com/user-attachments/assets/a51d8f03-32d5-4f89-9b9b-2b7046c7b1f2)
(note: that's only one array (10.8 kWp) - the other one is very small (0.7 kWp) and can be ignore)

Log after instance restart:
![grafik](https://github.com/user-attachments/assets/8baea7e8-6e85-4fff-872a-f83078f35fa1)

Updated objects:
![grafik](https://github.com/user-attachments/assets/b6fc896f-0515-4575-93df-2d2550d78d71)

As a restart updates the values, a full consumption of API calls mustn't be the reason.

Thanks in advance 4 any help!

BR
Chris

### iobroker.current.log (in debug mode!)

![grafik](https://github.com/user-attachments/assets/81b9bca5-c62e-45bc-9509-9efdd0bfb935)

### Version of nodejs

20.17.0

### Version of ioBroker js-controller

6.0.11

### Version of adapter

3.0.0

**Comment by alx785** [comment]
@n4pstarr i don´t know why there is no automatic refresh when you chose solcast, like it is in forecast.solar but for me the following workaroud helps to get new data from the api:
use a script that cron´s the refresh button. That button is located in the service folder. Try not to refresh to often, because of the maximum count of calls per day. For me it works nice with a daily cron job from 7:00 till 19:00 every two hours.

![image](https://github.com/user-attachments/assets/eff74cdc-09f5-414c-a84c-4d9b8b1db03c)

**Comment by klein0r** [comment]
At the moment, the data is just fetched once a day:

https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/3ef9743f113e0c4a53a7f1841748131e5b1d66a3/main.js#L241-L244

The reason is, that the response doesn't contain values in the past. Which leads to "unfilled" states.

**Comment by klein0r** [comment]
> use a script that cron´s the refresh button.

States with role `button` shouldn't be controlled with `false`. "Umschalten" is not correct. Just set `true`.

**Comment by alx785** [comment]
@klein0r Thank you for that little hint and your work Matthias!

**Comment by n4pstarr** [comment]
@alx785 : thanks a lot fot that hint. Thats's a workaround - but a fine one ;)
