### ISSUE TITLE
FollowUp:  Axios Error AxiosError: Request failed with status code 403 

### ISSUE THREAD

**Issue by michiproep** [iobroker-community-adapters/ioBroker.pvforecast#180]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Used integration

solcast

### The problem

nachdem das ursprüngliche Issue gelocked wurde...
@mcm1957 Das muss man schon diskutieren dürfen. Es könnte ja theoretisch ein Bug im Adapter sein, oder nicht?

### Version of nodejs

v20.17.0

### Version of ioBroker js-controller

xx

### Version of adapter

v4

**Comment by michiproep** [comment]
https://github.com/iobroker-community-adapters/ioBroker.pvforecast/issues/177

**Comment by mcm1957** [comment]
**If you expect a issue, please open a NEW issue, describe the problem, add version information and attach a log.**

Discussions at CLOSED issues are not useful.
