### ISSUE TITLE
Import in InfluxDB funktioniert nicht

### ISSUE THREAD

**Issue by Streifi89** [iobroker-community-adapters/ioBroker.pvforecast#23]
Influx-Instanz im Adapter aktiviert. Influx-Adapter nochmals erfolgreich getestet. Ich finde in meiner InfluxDB aber keine Measurements. 

Auch der Logeintrag "this.log.debug(`influxDB storeState into "${influxinstance}": value "${value}" of "${datapoint}" with timestamp ${timestamp}`);" fehlt - der müsste ja erscheinen.

Influx-Instanz ab- und wieder anwählen mit speichern zwischendrin funktioniert leider auch nicht. 

Idee?

**Comment by themuck** [comment]
kann ich bestätigen... geht bei mir auch nicht.

**Comment by bastian-mer** [comment]
Dito - ebenfalls bei mir.

**Comment by allesgutewarweg** [comment]
Bei mir tut sich ebenfalls nichts

**Comment by allesgutewarweg** [comment]
Bei mir tat sich ebenfalls nichts, ich konnte das Problem aber mit ganz viel Tape flicken. Nun muss jemand ran der sauber Programmieren kann :)

Im Forum fand sich ein Hinweis, dass dieses Problem erst seit v1.0 auftritt. Also habe ich die Funktion addToInfluxDB aus der v0.2.7 in meine main.js kopiert die sich in /opt/iobroker/node_modules/iobroker.pvforecast/main.js befindet.

Mit der folgenden Funktion läufts bei mir:

```
        async addToInfluxDB(datapoint,timestamp,value) {
                try {
                        let influxinstance = this.config.influxinstace;

                        if (influxinstance === '') return;

                        // Fallback for older instance configs
                        if (influxinstance.indexOf('influxdb.') !== 0) {
                                influxinstance = `influxdb.${influxinstance}`;
                        }

                        this.log.debug(`influxDB storeState into "${influxinstance}": value "${value}" of "${datapoint}" with timestamp ${timestamp}`);

                        this.sendTo(influxinstance, 'storeState', {
                                id: datapoint,
                                state: {
                                        ts: timestamp,
                                        val: value,
                                        ack: true,
                                        from: 'system.adapter.' + this.namespace,
                                        //q: 0
                                }
                        });
                } catch (e) {
                        this.log.error('Datenbank: ' + e);
                }
        }
```

Die Daten werden nun fehlerfrei in die Influx geschrieben und könne von dort weiter verarbeitet werden.

**Comment by klein0r** [comment]
@allesgutewarweg Mit welcher Version der InfluxDB und mit welcher Version des InfluxDB-Adpaters wurde das getestet?

Bin gerade an einem Fix hierfür, aber es wird nichts gepeichert. Nutze

- InfluxDB 2.1.1
- InfluxDB-Adapter 3.0.2

**Comment by allesgutewarweg** [comment]
Meine Installation ist schon älter und läuft daher mit 

- InfluxDB Version: 1.8.10
- InfluxDB-Adapter: 2.6.3

Da ich das Stable-Repo verwende sehe den InfluxDB-Adapter 3.0.2 nicht.

Ich sage schon mal vielen Dank! :)

**Comment by klein0r** [comment]
Okay liegt wohl noch an der InfluxDB-Adapter 3.x version. Da wurde ja extrem viel umgebaut.

Ich veröffentliche jetzt erstmal eine 1.1.0
Sollte mit InfluxDB-Adapter < 3 laufen

**Comment by Diginix** [comment]
@klein0r Wäre cool wenn bei dem Release direkt noch das Runden aller Werte in pvforecast.0.1.JSONTable mit reinkäme.
Werte wie 2039.0000000000002 Watt machen sich in der VIS nicht schön. ;-)

**Comment by kopierschnitte** [comment]
Mit dem Influx-Adapter 2.x klappt es bei mir. Danke für den Tipp!

**Comment by Foradh** [comment]
Mit der pvforecast Version 2.1.1 funktioniert der Übertrag in die InfluxDB wieder einwandfrei!
@klein0r 
Ist est möglich den Übertrag auch für die Summary Werte zu aktivieren? Das würde in der Visualisierung bei Grafana einiges vereinfachen.

**Comment by kopierschnitte** [comment]
@Foradh Ich habe es in Grafana einfach so gelöst, dass ich eine "Expression" (math) hinzugefügt habe, die einfach $A+$B lautet. Ist recht einfach ;-)

**Comment by klein0r** [comment]
> Ist est möglich den Übertrag auch für die Summary Werte zu aktivieren? Das würde in der Visualisierung bei Grafana einiges vereinfachen.

Ja klar, wäre kein Problem. Kann ich gern mit aufnehmen für die nächste Version

**Comment by allesgutewarweg** [comment]
Mit der pvforecast Version 2.1.1 funktioniert der Übertrag in die InfluxDB auch bei mir wieder einwandfrei!

Vielen Dank :)
