### ISSUE TITLE
Die JSONGraph unter summary wird nicht gefüllt

### ISSUE THREAD

**Issue by SpezialAgent** [iobroker-community-adapters/ioBroker.pvforecast#25]
### The problem

Die JSONTable wird gefüllt, die anderen Werte auch. Interessanterweise werden die JSONGraph in den Anlagen (Ost, West und Süd) gefüllt. Nur die Summe unter summary bleibt leer.
PlatformBetriebssystem:linux
Architektur:x64
CPUs:2
Geschwindigkeit:2207 MHz
Modell:Common KVM processor
RAM:3.8 GB
System-Betriebszeit:1 T. 17:58:19
Node.js:v14.19.3
time:1653195124456
timeOffset:-120
Adapter-Anzahl:499
NPM:6.14.17
Datenträgergröße:28.4 GB
freier Festplattenspeicher:19.6 GB
Betriebszeit:1 T. 17:58:14
Aktive Instanzen:18
Pfad:/opt/iobroker/

### Version of nodejs

v14.19.3

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.1.0

### Operating system running ioBroker

Linux Debian 11

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

[pvforecast-debug.txt](https://github.com/iobroker-community-adapters/ioBroker.pvforecast/files/8748787/pvforecast-debug.txt)

**Comment by SpezialAgent** [comment]
Die Version 1.0.1 auf meinem Produktivsystem läuft einwandfrei und erstellt unter summary auch die JSONGraph.

**Comment by klein0r** [comment]
Die checkbox für charting muss aktiviert werden. Die war zwar vorher vorhanden, aber ohne Funktion 🤷‍♂️

**Comment by SpezialAgent** [comment]
Das wars. Vielen Dank!

Gruß
Martin
