### ISSUE TITLE
The solcast api response is in UTC Time

### ISSUE THREAD

**Issue by Morluktom** [iobroker-community-adapters/ioBroker.pvforecast#26]
### The problem

The solcast api response is in UTC Time. So the adapter has to convert the time to local time.

### Version of nodejs

14.18.2

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.1.4

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/34573701/171550072-853afe79-f565-4c46-96be-6494f262ed0d.png)

**Comment by klein0r** [comment]
You're right. I've compared the output of forecast.solar with Solcast:

<img width="934" alt="Screenshot 2022-06-02 at 09 14 06" src="https://user-images.githubusercontent.com/1959049/171574395-fe8eb5aa-25f5-4479-9c8e-c9022a90b9b4.png">

**Comment by klein0r** [comment]
The response for a Solcast Timestamp is ``2022-05-23T09:00:00.0000000Z``

The solcast script manipulates the time string:

https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/d8566db472d1f87d71e32fc4c2eeeac88e08b072/lib/solcast.js#L19

@MeisterTR implemented that in 3f26ff82110d27ee39609900e3cbf309a5ee64ab with the comment "update". I don't know the reason for the replacement, but that leads to the time shift.

I will remove that line in the next version (with added unit tests for different time zones).

**Comment by Morluktom** [comment]
I try the Github Version today.
Everythink looks fine.
Great Job,  thanks!

**Comment by klein0r** [comment]
Fixed in v2.1.5
