### ISSUE TITLE
Azimuth picture not shown in configuration at fresh installation

### ISSUE THREAD

**Issue by SBorg2014** [iobroker-community-adapters/ioBroker.pvforecast#27]
### The problem

IMO used wrong URL: .../adapter/pvforecast/adapter/pvforecast/img/Azimuth.png
and should be .../adapter/pvforecast/img/Azimuth.png

### Version of nodejs

14.19.3

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.1.4

### Operating system running ioBroker

Ubuntu 20.04.4 LTS

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Admin 6 Beta?
I've reported the wrong behaviour (Admin 5) here: https://github.com/ioBroker/ioBroker.admin/issues/1470

**Comment by SBorg2014** [comment]
Hello Matthias, yes. Admin 6 --> solved (Admin Issue)
Maybe (before i create an unnessesary issue) this is also an Admin-Issue. If i've activated expertmode, then it's not possible to install a instance of pvforecast. It throws "Invalid version of js-controller. Required >=3.3.22. Current 4.0.23"

**Comment by klein0r** [comment]
So this is not a issue for pvforecast - admin has to fix that ([see last comment](https://github.com/ioBroker/ioBroker.admin/issues/1470#issuecomment-1146604978)).

If I change the url now, it will not work in Admin 5 anymore. So the minimum required version of admin would be 6.0.0 (which is a very fresh beta).

**Comment by SBorg2014** [comment]
Admin 6 Issue

**Comment by klein0r** [comment]
Fixed (tested with admin v6.1.5)
