### ISSUE TITLE
Neigung von 0 nicht erlaubt

### ISSUE THREAD

**Issue by BernhardLinz** [iobroker-community-adapters/ioBroker.pvforecast#32]
### The problem

Wenn in einer Anlage eine Neigung von 0 Grad einstelle gibt es einen Fehler im Log:

`2022-06-22 13:26:09.417  - error: pvforecast.0 (2602203) Error: Invalid device configuration: Found plant without tilt`

![image](https://user-images.githubusercontent.com/31903932/175018614-d818998a-7258-4126-ab02-043db8e7a5b4.png)

### Version of nodejs

v14.19.3

### Version of ioBroker js-controller

 4.0.23

### Version of Adapter

v2.2.0

### Operating system running ioBroker

Ubuntu 20.04 LTS

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Danke! Gucke ich mir an
