### ISSUE TITLE
Plant is not editable

### ISSUE THREAD

**Issue by danielthoene** [iobroker-community-adapters/ioBroker.pvforecast#38]
### The problem

Hi!
I can only change the azimut of my plant. Everything else seems to be write-only...

The adapter itself works fine though.

The log (debug) doesn't show any errors / warnings.

Bye!
Daniel

### Version of nodejs

v16.16.0

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.3.0

### Operating system running ioBroker

Ubuntu Server 22.04

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
It's an admin issue in 6.2.0 and 6.2.1. See https://github.com/ioBroker/ioBroker.admin/issues/1589
