### ISSUE TITLE
not able to delete the first number in configuration of the PV system - workarount avaiable

### ISSUE THREAD

**Issue by DieWaldfee** [iobroker-community-adapters/ioBroker.pvforecast#69]
### The problem

while entering the values for my solar system in the configuration tab the first values in anzimut, deg, ... are not deletable via backspace. If you mark the values with the mouse an type an number, it works fine.
example: degree = 40 (default) the 0 is deletable, the 4 is remaining. entering 30 behind and delete the first 4 will work and mark the 40 with the mouse an write 30 will work too.

I think, its just a small think :-)

The adapter itself works fine - thanks this great work!
...and thanks for Matthias Kleine for his infos and the reference to this adapter :-)

with best regards
Die Waldfee 

### Version of nodejs

16.17.1

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.3.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

no error in the log for this small bug.

**Comment by klein0r** [comment]
Admin bug. See https://github.com/ioBroker/ioBroker.admin/issues/1768
