### ISSUE TITLE
Weather with API-Key not working

### ISSUE THREAD

**Issue by tomschlde** [iobroker-community-adapters/ioBroker.pvforecast#88]
### The problem

<html>
<body>

pvforecast.0 | 2023-02-15 14:16:52.707 | error | [updateActualWeatherData] failed to update weather data: TypeError: data.filter is not a function
-- | -- | -- | --
pvforecast.0 | 2023-02-15 14:16:49.214 | error | Axios Error AxiosError: Request failed with status code 400

</body>
</html>

### Version of nodejs

v14.20.1 

### Version of ioBroker js-controller

4.0.24

### Version of Adapter

v2.3.0

### Operating system running ioBroker

Linux raspberrypi 5.10.103-v7l+

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

`<html>
<body>

pvforecast.0 | 2023-02-15 14:36:48.398 | debug | [updateActualDataCron] next execution: 2023-02-15T14:45:00.000+01:00
-- | -- | -- | --
pvforecast.0 | 2023-02-15 14:36:48.365 | info | Starting update cron (every 15 Minutes) for timezone: Europe/Berlin
pvforecast.0 | 2023-02-15 14:36:48.283 | error | [updateActualWeatherData] failed to update weather data: TypeError: data.filter is not a function
pvforecast.0 | 2023-02-15 14:36:46.774 | debug | global time: {"pv":[{"dayOfMonth":15,"time":"08:00:00","value":0.981},{"dayOfMonth":15,"time":"09:00:00","value":2.385},{"dayOfMonth":15,"time":"10:00:00","value":4.141},{"dayOfMonth":15,"time":"11:00:00","value":5.318},{"dayOfMonth":15,"time":"12:00:00","value":5.875},{"dayOfMonth":15,"time":"13:00:00","value":5.503},{"dayOfMonth":15,"time":"14:00:00","value":4.805},{"dayOfMonth":15,"time":"15:00:00","value":3.623},{"dayOfMonth":15,"time":"16:00:00","value":1.653},{"dayOfMonth":15,"time":"17:00:00","value":0.651},{"dayOfMonth":16,"time":"08:00:00","value":0.906},{"dayOfMonth":16,"time":"09:00:00","value":1.172},{"dayOfMonth":16,"time":"10:00:00","value":1.083},{"dayOfMonth":16,"time":"11:00:00","value":1.396},{"dayOfMonth":16,"time":"12:00:00","value":1.653},{"dayOfMonth":16,"time":"13:00:00","value":1.654},{"dayOfMonth":16,"time":"14:00:00","value":1.217},{"dayOfMonth":16,"time":"15:00:00","value":0.827},{"dayOfMonth":16,"time":"16:00:00","value":0.513},{"dayOfMonth":16,"time":"17:00:00","value":0.319}]}
pvforecast.0 | 2023-02-15 14:36:46.699 | debug | finished plants update
pvforecast.0 | 2023-02-15 14:36:46.698 | debug | finished plant update: "PV"
pvforecast.0 | 2023-02-15 14:36:46.684 | debug | generated JSON graph of "PV": {"data":[0,0.981,1.646,2.385,3.282,4.141,4.762,5.318,5.685,5.875,5.773,5.503,5.211,4.805,4.284,3.623,2.782,1.653,1.162,0.651,0.262,0,0,0.906,1.093,1.172,1.093,1.083,1.227,1.396,1.581,1.653,1.716,1.654,1.465,1.217,1.04,0.827,0.627,0.513,0.421,0.319,0.199,0,0,0.179,0.263,0.352,0.427,0.494,0.638,0.699,0.739,0.757,0.768,0.764,0.762,0.75,0.703,0.65,0.58,0.502,0.411,0.309,0.2,0,0,0.228,0.319,0.404,0.492,0.573,0.64,0.702,0.743,0.761,0.773,0.82,0.856,0.83,0.801,0.736,0.686,0.61,0.488,0.352,0.226,0],"type":"bar","legendText":"PV","displayOrder":1,"color":"#2072cc","tooltip_AppendText":"kW","datalabel_show":true,"datalabel_rotation":270,"datalabel_color":"#050505","datalabel_fontSize":12,"barIsStacked":true,"barStackId":1,"yAxis_id":0,"yAxis_position":"left","yAxis_show":true,"yAxis_appendix":"kW","yAxis_step":1}
pvforecast.0 | 2023-02-15 14:36:46.654 | debug | generated JSON table of "PV": [{"Time":"2023-02-15 07:44:00","Power":"0,000"},{"Time":"2023-02-15 08:00:00","Power":"0,981"},{"Time":"2023-02-15 08:30:00","Power":"1,646"},{"Time":"2023-02-15 09:00:00","Power":"2,385"},{"Time":"2023-02-15 09:30:00","Power":"3,282"},{"Time":"2023-02-15 10:00:00","Power":"4,141"},{"Time":"2023-02-15 10:30:00","Power":"4,762"},{"Time":"2023-02-15 11:00:00","Power":"5,318"},{"Time":"2023-02-15 11:30:00","Power":"5,685"},{"Time":"2023-02-15 12:00:00","Power":"5,875"},{"Time":"2023-02-15 12:30:00","Power":"5,773"},{"Time":"2023-02-15 13:00:00","Power":"5,503"},{"Time":"2023-02-15 13:30:00","Power":"5,211"},{"Time":"2023-02-15 14:00:00","Power":"4,805"},{"Time":"2023-02-15 14:30:00","Power":"4,284"},{"Time":"2023-02-15 15:00:00","Power":"3,623"},{"Time":"2023-02-15 15:30:00","Power":"2,782"},{"Time":"2023-02-15 16:00:00","Power":"1,653"},{"Time":"2023-02-15 16:30:00","Power":"1,162"},{"Time":"2023-02-15 17:00:00","Power":"0,651"},{"Time":"2023-02-15 17:30:00","Power":"0,262"},{"Time":"2023-02-15 17:50:00","Power":"0,000"},{"Time":"2023-02-16 07:42:00","Power":"0,000"},{"Time":"2023-02-16 08:00:00","Power":"0,906"},{"Time":"2023-02-16 08:30:00","Power":"1,093"},{"Time":"2023-02-16 09:00:00","Power":"1,172"},{"Time":"2023-02-16 09:30:00","Power":"1,093"},{"Time":"2023-02-16 10:00:00","Power":"1,083"},{"Time":"2023-02-16 10:30:00","Power":"1,227"},{"Time":"2023-02-16 11:00:00","Power":"1,396"},{"Time":"2023-02-16 11:30:00","Power":"1,581"},{"Time":"2023-02-16 12:00:00","Power":"1,653"},{"Time":"2023-02-16 12:30:00","Power":"1,716"},{"Time":"2023-02-16 13:00:00","Power":"1,654"},{"Time":"2023-02-16 13:30:00","Power":"1,465"},{"Time":"2023-02-16 14:00:00","Power":"1,217"},{"Time":"2023-02-16 14:30:00","Power":"1,040"},{"Time":"2023-02-16 15:00:00","Power":"0,827"},{"Time":"2023-02-16 15:30:00","Power":"0,627"},{"Time":"2023-02-16 16:00:00","Power":"0,513"},{"Time":"2023-02-16 16:30:00","Power":"0,421"},{"Time":"2023-02-16 17:00:00","Power":"0,319"},{"Time":"2023-02-16 17:30:00","Power":"0,199"},{"Time":"2023-02-16 17:52:00","Power":"0,000"},{"Time":"2023-02-17 07:40:00","Power":"0,000"},{"Time":"2023-02-17 08:00:00","Power":"0,179"},{"Time":"2023-02-17 08:30:00","Power":"0,263"},{"Time":"2023-02-17 09:00:00","Power":"0,352"},{"Time":"2023-02-17 09:30:00","Power":"0,427"},{"Time":"2023-02-17 10:00:00","Power":"0,494"},{"Time":"2023-02-17 10:30:00","Power":"0,638"},{"Time":"2023-02-17 11:00:00","Power":"0,699"},{"Time":"2023-02-17 11:30:00","Power":"0,739"},{"Time":"2023-02-17 12:00:00","Power":"0,757"},{"Time":"2023-02-17 12:30:00","Power":"0,768"},{"Time":"2023-02-17 13:00:00","Power":"0,764"},{"Time":"2023-02-17 13:30:00","Power":"0,762"},{"Time":"2023-02-17 14:00:00","Power":"0,750"},{"Time":"2023-02-17 14:30:00","Power":"0,703"},{"Time":"2023-02-17 15:00:00","Power":"0,650"},{"Time":"2023-02-17 15:30:00","Power":"0,580"},{"Time":"2023-02-17 16:00:00","Power":"0,502"},{"Time":"2023-02-17 16:30:00","Power":"0,411"},{"Time":"2023-02-17 17:00:00","Power":"0,309"},{"Time":"2023-02-17 17:30:00","Power":"0,200"},{"Time":"2023-02-17 17:54:00","Power":"0,000"},{"Time":"2023-02-18 07:39:00","Power":"0,000"},{"Time":"2023-02-18 08:00:00","Power":"0,228"},{"Time":"2023-02-18 08:30:00","Power":"0,319"},{"Time":"2023-02-18 09:00:00","Power":"0,404"},{"Time":"2023-02-18 09:30:00","Power":"0,492"},{"Time":"2023-02-18 10:00:00","Power":"0,573"},{"Time":"2023-02-18 10:30:00","Power":"0,640"},{"Time":"2023-02-18 11:00:00","Power":"0,702"},{"Time":"2023-02-18 11:30:00","Power":"0,743"},{"Time":"2023-02-18 12:00:00","Power":"0,761"},{"Time":"2023-02-18 12:30:00","Power":"0,773"},{"Time":"2023-02-18 13:00:00","Power":"0,820"},{"Time":"2023-02-18 13:30:00","Power":"0,856"},{"Time":"2023-02-18 14:00:00","Power":"0,830"},{"Time":"2023-02-18 14:30:00","Power":"0,801"},{"Time":"2023-02-18 15:00:00","Power":"0,736"},{"Time":"2023-02-18 15:30:00","Power":"0,686"},{"Time":"2023-02-18 16:00:00","Power":"0,610"},{"Time":"2023-02-18 16:30:00","Power":"0,488"},{"Time":"2023-02-18 17:00:00","Power":"0,352"},{"Time":"2023-02-18 17:30:00","Power":"0,226"},{"Time":"2023-02-18 17:56:00","Power":"0,000"}]
pvforecast.0 | 2023-02-15 14:36:46.635 | debug | generated JSON data of "PV": [{"t":1676443440000,"y":0},{"t":1676444400000,"y":0.981},{"t":1676446200000,"y":1.646},{"t":1676448000000,"y":2.385},{"t":1676449800000,"y":3.282},{"t":1676451600000,"y":4.141},{"t":1676453400000,"y":4.762},{"t":1676455200000,"y":5.318},{"t":1676457000000,"y":5.685},{"t":1676458800000,"y":5.875},{"t":1676460600000,"y":5.773},{"t":1676462400000,"y":5.503},{"t":1676464200000,"y":5.211},{"t":1676466000000,"y":4.805},{"t":1676467800000,"y":4.284},{"t":1676469600000,"y":3.623},{"t":1676471400000,"y":2.782},{"t":1676473200000,"y":1.653},{"t":1676475000000,"y":1.162},{"t":1676476800000,"y":0.651},{"t":1676478600000,"y":0.262},{"t":1676479800000,"y":0},{"t":1676529720000,"y":0},{"t":1676530800000,"y":0.906},{"t":1676532600000,"y":1.093},{"t":1676534400000,"y":1.172},{"t":1676536200000,"y":1.093},{"t":1676538000000,"y":1.083},{"t":1676539800000,"y":1.227},{"t":1676541600000,"y":1.396},{"t":1676543400000,"y":1.581},{"t":1676545200000,"y":1.653},{"t":1676547000000,"y":1.716},{"t":1676548800000,"y":1.654},{"t":1676550600000,"y":1.465},{"t":1676552400000,"y":1.217},{"t":1676554200000,"y":1.04},{"t":1676556000000,"y":0.827},{"t":1676557800000,"y":0.627},{"t":1676559600000,"y":0.513},{"t":1676561400000,"y":0.421},{"t":1676563200000,"y":0.319},{"t":1676565000000,"y":0.199},{"t":1676566320000,"y":0},{"t":1676616000000,"y":0},{"t":1676617200000,"y":0.179},{"t":1676619000000,"y":0.263},{"t":1676620800000,"y":0.352},{"t":1676622600000,"y":0.427},{"t":1676624400000,"y":0.494},{"t":1676626200000,"y":0.638},{"t":1676628000000,"y":0.699},{"t":1676629800000,"y":0.739},{"t":1676631600000,"y":0.757},{"t":1676633400000,"y":0.768},{"t":1676635200000,"y":0.764},{"t":1676637000000,"y":0.762},{"t":1676638800000,"y":0.75},{"t":1676640600000,"y":0.703},{"t":1676642400000,"y":0.65},{"t":1676644200000,"y":0.58},{"t":1676646000000,"y":0.502},{"t":1676647800000,"y":0.411},{"t":1676649600000,"y":0.309},{"t":1676651400000,"y":0.2},{"t":1676652840000,"y":0},{"t":1676702340000,"y":0},{"t":1676703600000,"y":0.228},{"t":1676705400000,"y":0.319},{"t":1676707200000,"y":0.404},{"t":1676709000000,"y":0.492},{"t":1676710800000,"y":0.573},{"t":1676712600000,"y":0.64},{"t":1676714400000,"y":0.702},{"t":1676716200000,"y":0.743},{"t":1676718000000,"y":0.761},{"t":1676719800000,"y":0.773},{"t":1676721600000,"y":0.82},{"t":1676723400000,"y":0.856},{"t":1676725200000,"y":0.83},{"t":1676727000000,"y":0.801},{"t":1676728800000,"y":0.736},{"t":1676730600000,"y":0.686},{"t":1676732400000,"y":0.61},{"t":1676734200000,"y":0.488},{"t":1676736000000,"y":0.352},{"t":1676737800000,"y":0.226},{"t":1676739360000,"y":0}]
pvforecast.0 | 2023-02-15 14:36:46.615 | debug | [saveEveryHourEmptyStates] 7 items missing - please check if your license allows to request all values
pvforecast.0 | 2023-02-15 14:36:46.614 | debug | [saveEveryHourEmptyStates] 7 items missing - please check if your license allows to request all values
pvforecast.0 | 2023-02-15 14:36:45.795 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.17:00:00 - value: 0.319
pvforecast.0 | 2023-02-15 14:36:45.763 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.16:00:00 - value: 0.513
pvforecast.0 | 2023-02-15 14:36:45.723 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.15:00:00 - value: 0.827
pvforecast.0 | 2023-02-15 14:36:45.683 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.14:00:00 - value: 1.217
pvforecast.0 | 2023-02-15 14:36:45.623 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.13:00:00 - value: 1.654
pvforecast.0 | 2023-02-15 14:36:45.588 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.12:00:00 - value: 1.653
pvforecast.0 | 2023-02-15 14:36:45.555 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.11:00:00 - value: 1.396
pvforecast.0 | 2023-02-15 14:36:45.522 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.10:00:00 - value: 1.083
pvforecast.0 | 2023-02-15 14:36:45.485 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.09:00:00 - value: 1.172
pvforecast.0 | 2023-02-15 14:36:45.451 | debug | [saveEveryHour] found time plants.pv.power.hoursTomorrow.08:00:00 - value: 0.906
pvforecast.0 | 2023-02-15 14:36:45.386 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.17:00:00 - value: 0.651
pvforecast.0 | 2023-02-15 14:36:45.345 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.16:00:00 - value: 1.653
pvforecast.0 | 2023-02-15 14:36:45.311 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.15:00:00 - value: 3.623
pvforecast.0 | 2023-02-15 14:36:45.278 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.14:00:00 - value: 4.805
pvforecast.0 | 2023-02-15 14:36:45.245 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.13:00:00 - value: 5.503
pvforecast.0 | 2023-02-15 14:36:45.210 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.12:00:00 - value: 5.875
pvforecast.0 | 2023-02-15 14:36:45.174 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.11:00:00 - value: 5.318
pvforecast.0 | 2023-02-15 14:36:45.136 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.10:00:00 - value: 4.141
pvforecast.0 | 2023-02-15 14:36:45.098 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.09:00:00 - value: 2.385
pvforecast.0 | 2023-02-15 14:36:45.040 | debug | [saveEveryHour] found time plants.pv.power.hoursToday.08:00:00 - value: 0.981
pvforecast.0 | 2023-02-15 14:36:45.005 | debug | [updateActualDataInterval] current service data for plants.pv.service.data ("PV"): {"watts":{"2023-02-15 07:44:00":0,"2023-02-15 08:00:00":981,"2023-02-15 08:30:00":1646,"2023-02-15 09:00:00":2385,"2023-02-15 09:30:00":3282,"2023-02-15 10:00:00":4141,"2023-02-15 10:30:00":4762,"2023-02-15 11:00:00":5318,"2023-02-15 11:30:00":5685,"2023-02-15 12:00:00":5875,"2023-02-15 12:30:00":5773,"2023-02-15 13:00:00":5503,"2023-02-15 13:30:00":5211,"2023-02-15 14:00:00":4805,"2023-02-15 14:30:00":4284,"2023-02-15 15:00:00":3623,"2023-02-15 15:30:00":2782,"2023-02-15 16:00:00":1653,"2023-02-15 16:30:00":1162,"2023-02-15 17:00:00":651,"2023-02-15 17:30:00":262,"2023-02-15 17:50:00":0,"2023-02-16 07:42:00":0,"2023-02-16 08:00:00":906,"2023-02-16 08:30:00":1093,"2023-02-16 09:00:00":1172,"2023-02-16 09:30:00":1093,"2023-02-16 10:00:00":1083,"2023-02-16 10:30:00":1227,"2023-02-16 11:00:00":1396,"2023-02-16 11:30:00":1581,"2023-02-16 12:00:00":1653,"2023-02-16 12:30:00":1716,"2023-02-16 13:00:00":1654,"2023-02-16 13:30:00":1465,"2023-02-16 14:00:00":1217,"2023-02-16 14:30:00":1040,"2023-02-16 15:00:00":827,"2023-02-16 15:30:00":627,"2023-02-16 16:00:00":513,"2023-02-16 16:30:00":421,"2023-02-16 17:00:00":319,"2023-02-16 17:30:00":199,"2023-02-16 17:52:00":0,"2023-02-17 07:40:00":0,"2023-02-17 08:00:00":179,"2023-02-17 08:30:00":263,"2023-02-17 09:00:00":352,"2023-02-17 09:30:00":427,"2023-02-17 10:00:00":494,"2023-02-17 10:30:00":638,"2023-02-17 11:00:00":699,"2023-02-17 11:30:00":739,"2023-02-17 12:00:00":757,"2023-02-17 12:30:00":768,"2023-02-17 13:00:00":764,"2023-02-17 13:30:00":762,"2023-02-17 14:00:00":750,"2023-02-17 14:30:00":703,"2023-02-17 15:00:00":650,"2023-02-17 15:30:00":580,"2023-02-17 16:00:00":502,"2023-02-17 16:30:00":411,"2023-02-17 17:00:00":309,"2023-02-17 17:30:00":200,"2023-02-17 17:54:00":0,"2023-02-18 07:39:00":0,"2023-02-18 08:00:00":228,"2023-02-18 08:30:00":319,"2023-02-18 09:00:00":404,"2023-02-18 09:30:00":492,"2023-02-18 10:00:00":573,"2023-02-18 10:30:00":640,"2023-02-18 11:00:00":702,"2023-02-18 11:30:00":743,"2023-02-18 12:00:00":761,"2023-02-18 12:30:00":773,"2023-02-18 13:00:00":820,"2023-02-18 13:30:00":856,"2023-02-18 14:00:00":830,"2023-02-18 14:30:00":801,"2023-02-18 15:00:00":736,"2023-02-18 15:30:00":686,"2023-02-18 16:00:00":610,"2023-02-18 16:30:00":488,"2023-02-18 17:00:00":352,"2023-02-18 17:30:00":226,"2023-02-18 17:56:00":0},"watt_hours_period":{"2023-02-15 07:44:00":0,"2023-02-15 08:00:00":131,"2023-02-15 08:30:00":657,"2023-02-15 09:00:00":1008,"2023-02-15 09:30:00":1417,"2023-02-15 10:00:00":1856,"2023-02-15 10:30:00":2226,"2023-02-15 11:00:00":2520,"2023-02-15 11:30:00":2751,"2023-02-15 12:00:00":2890,"2023-02-15 12:30:00":2912,"2023-02-15 13:00:00":2819,"2023-02-15 13:30:00":2679,"2023-02-15 14:00:00":2504,"2023-02-15 14:30:00":2272,"2023-02-15 15:00:00":1977,"2023-02-15 15:30:00":1601,"2023-02-15 16:00:00":1109,"2023-02-15 16:30:00":704,"2023-02-15 17:00:00":453,"2023-02-15 17:30:00":228,"2023-02-15 17:50:00":44,"2023-02-16 07:42:00":0,"2023-02-16 08:00:00":136,"2023-02-16 08:30:00":500,"2023-02-16 09:00:00":566,"2023-02-16 09:30:00":566,"2023-02-16 10:00:00":544,"2023-02-16 10:30:00":578,"2023-02-16 11:00:00":656,"2023-02-16 11:30:00":744,"2023-02-16 12:00:00":809,"2023-02-16 12:30:00":842,"2023-02-16 13:00:00":843,"2023-02-16 13:30:00":780,"2023-02-16 14:00:00":671,"2023-02-16 14:30:00":564,"2023-02-16 15:00:00":467,"2023-02-16 15:30:00":364,"2023-02-16 16:00:00":285,"2023-02-16 16:30:00":234,"2023-02-16 17:00:00":185,"2023-02-16 17:30:00":130,"2023-02-16 17:52:00":36,"2023-02-17 07:40:00":0,"2023-02-17 08:00:00":30,"2023-02-17 08:30:00":111,"2023-02-17 09:00:00":154,"2023-02-17 09:30:00":195,"2023-02-17 10:00:00":230,"2023-02-17 10:30:00":283,"2023-02-17 11:00:00":334,"2023-02-17 11:30:00":360,"2023-02-17 12:00:00":374,"2023-02-17 12:30:00":381,"2023-02-17 13:00:00":383,"2023-02-17 13:30:00":382,"2023-02-17 14:00:00":378,"2023-02-17 14:30:00":363,"2023-02-17 15:00:00":338,"2023-02-17 15:30:00":308,"2023-02-17 16:00:00":271,"2023-02-17 16:30:00":228,"2023-02-17 17:00:00":180,"2023-02-17 17:30:00":127,"2023-02-17 17:54:00":40,"2023-02-18 07:39:00":0,"2023-02-18 08:00:00":40,"2023-02-18 08:30:00":137,"2023-02-18 09:00:00":181,"2023-02-18 09:30:00":224,"2023-02-18 10:00:00":266,"2023-02-18 10:30:00":303,"2023-02-18 11:00:00":336,"2023-02-18 11:30:00":361,"2023-02-18 12:00:00":376,"2023-02-18 12:30:00":384,"2023-02-18 13:00:00":398,"2023-02-18 13:30:00":419,"2023-02-18 14:00:00":422,"2023-02-18 14:30:00":408,"2023-02-18 15:00:00":384,"2023-02-18 15:30:00":356,"2023-02-18 16:00:00":324,"2023-02-18 16:30:00":275,"2023-02-18 17:00:00":210,"2023-02-18 17:30:00":145,"2023-02-18 17:56:00":49},"watt_hours":{"2023-02-15 07:44:00":0,"2023-02-15 08:00:00":131,"2023-02-15 08:30:00":788,"2023-02-15 09:00:00":1796,"2023-02-15 09:30:00":3213,"2023-02-15 10:00:00":5069,"2023-02-15 10:30:00":7295,"2023-02-15 11:00:00":9815,"2023-02-15 11:30:00":12566,"2023-02-15 12:00:00":15456,"2023-02-15 12:30:00":18368,"2023-02-15 13:00:00":21187,"2023-02-15 13:30:00":23866,"2023-02-15 14:00:00":26370,"2023-02-15 14:30:00":28642,"2023-02-15 15:00:00":30619,"2023-02-15 15:30:00":32220,"2023-02-15 16:00:00":33329,"2023-02-15 16:30:00":34033,"2023-02-15 17:00:00":34486,"2023-02-15 17:30:00":34714,"2023-02-15 17:50:00":34758,"2023-02-16 07:42:00":0,"2023-02-16 08:00:00":136,"2023-02-16 08:30:00":636,"2023-02-16 09:00:00":1202,"2023-02-16 09:30:00":1768,"2023-02-16 10:00:00":2312,"2023-02-16 10:30:00":2890,"2023-02-16 11:00:00":3546,"2023-02-16 11:30:00":4290,"2023-02-16 12:00:00":5099,"2023-02-16 12:30:00":5941,"2023-02-16 13:00:00":6784,"2023-02-16 13:30:00":7564,"2023-02-16 14:00:00":8235,"2023-02-16 14:30:00":8799,"2023-02-16 15:00:00":9266,"2023-02-16 15:30:00":9630,"2023-02-16 16:00:00":9915,"2023-02-16 16:30:00":10149,"2023-02-16 17:00:00":10334,"2023-02-16 17:30:00":10464,"2023-02-16 17:52:00":10500,"2023-02-17 07:40:00":0,"2023-02-17 08:00:00":30,"2023-02-17 08:30:00":141,"2023-02-17 09:00:00":295,"2023-02-17 09:30:00":490,"2023-02-17 10:00:00":720,"2023-02-17 10:30:00":1003,"2023-02-17 11:00:00":1337,"2023-02-17 11:30:00":1697,"2023-02-17 12:00:00":2071,"2023-02-17 12:30:00":2452,"2023-02-17 13:00:00":2835,"2023-02-17 13:30:00":3217,"2023-02-17 14:00:00":3595,"2023-02-17 14:30:00":3958,"2023-02-17 15:00:00":4296,"2023-02-17 15:30:00":4604,"2023-02-17 16:00:00":4875,"2023-02-17 16:30:00":5103,"2023-02-17 17:00:00":5283,"2023-02-17 17:30:00":5410,"2023-02-17 17:54:00":5450,"2023-02-18 07:39:00":0,"2023-02-18 08:00:00":40,"2023-02-18 08:30:00":177,"2023-02-18 09:00:00":358,"2023-02-18 09:30:00":582,"2023-02-18 10:00:00":848,"2023-02-18 10:30:00":1151,"2023-02-18 11:00:00":1487,"2023-02-18 11:30:00":1848,"2023-02-18 12:00:00":2224,"2023-02-18 12:30:00":2608,"2023-02-18 13:00:00":3006,"2023-02-18 13:30:00":3425,"2023-02-18 14:00:00":3847,"2023-02-18 14:30:00":4255,"2023-02-18 15:00:00":4639,"2023-02-18 15:30:00":4995,"2023-02-18 16:00:00":5319,"2023-02-18 16:30:00":5594,"2023-02-18 17:00:00":5804,"2023-02-18 17:30:00":5949,"2023-02-18 17:56:00":5998},"watt_hours_day":{"2023-02-15":34758,"2023-02-16":10500,"2023-02-17":5450,"2023-02-18":5998}}
pvforecast.0 | 2023-02-15 14:36:44.999 | debug | [updateActualDataInterval] starting update
pvforecast.0 | 2023-02-15 14:36:44.997 | error | Axios Error AxiosError: Request failed with status code 400
pvforecast.0 | 2023-02-15 14:36:44.854 | debug | [updateServiceWeatherData] url (professional account only): https://api.forecast.solar/HgR47VmyCtL945ze/weather/50.942911/6.5644356
pvforecast.0 | 2023-02-15 14:36:44.854 | debug | received all data
pvforecast.0 | 2023-02-15 14:36:44.853 | debug | Last update of "PV" is within refresh interval - skipping
pvforecast.0 | 2023-02-15 14:36:44.850 | debug | plant "PV" - last update: 1676466836063, service url: https://api.forecast.solar/HgR47VmyCtL945ze/estimate/50.942911/6.5644356/45/20/9.49
pvforecast.0 | 2023-02-15 14:36:44.846 | debug | init done
pvforecast.0 | 2023-02-15 14:36:43.782 | debug | creating states for plant: "PV" (pv)
pvforecast.0 | 2023-02-15 14:36:43.763 | debug | creating states for weather
pvforecast.0 | 2023-02-15 14:36:43.756 | debug | The interval is set to 60 minutes
pvforecast.0 | 2023-02-15 14:36:43.755 | debug | Existing plant devices: [{"type":"device","common":{"name":"PV"},"native":{},"from":"system.adapter.pvforecast.0","user":"system.user.admin","ts":1676467007930,"_id":"pvforecast.0.plants.pv","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}] - configured: ["pvforecast.0.plants.pv"]
pvforecast.0 | 2023-02-15 14:36:43.692 | info | using system latitude: 50.942911 longitude: 6.5644356
pvforecast.0 | 2023-02-15 14:36:43.638 | debug | longitude and/or latitude not set, loading system configuration
pvforecast.0 | 2023-02-15 14:36:43.631 | debug | instance config: {"service":"forecastsolar","intervall":60,"apiKey":"HgR47VmyCtL945ze","weatherEnabled":true,"latitude":"","longitude":"","everyhourEnabled":true,"everyhourStepsize":"full","watt_kw":false,"influxinstace":"influxdb.0","chartingEnabled":true,"chartingJustToday":false,"chartingLabelFormat":"DD.MM. HH:mm","chartingLabelSize":12,"chartingRoation":270,"chartingAxisStepY":1,"devices":[{"name":"PV","azimuth":20,"tilt":45,"peakpower":9.49,"graphcolor":"#2072cc","labelcolor":"#050505"}]}
pvforecast.0 | 2023-02-15 14:36:43.593 | info | starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.pvforecast, node: v14.20.1, js-controller: 4.0.24
pvforecast.0 | 2023-02-15 14:36:37.628 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
pvforecast.0 | 2023-02-15 14:36:37.626 | info | terminating
pvforecast.0 | 2023-02-15 14:36:37.622 | info | Got terminate signal TERMINATE_YOURSELF
pvforecast.0 | 2023-02-15 14:30:04.384 | error | [updateActualWeatherData] failed to update weather data: TypeError: data.filter is not a function
pvforecast.0 | 2023-02-15 14:16:52.800 | info | Starting update cron (every 15 Minutes) for timezone: Europe/Berlin
pvforecast.0 | 2023-02-15 14:16:52.707 | error | [updateActualWeatherData] failed to update weather data: TypeError: data.filter is not a function
pvforecast.0 | 2023-02-15 14:16:49.214 | error | Axios Error AxiosError: Request failed with status code 400
pvforecast.0 | 2023-02-15 14:16:47.861 | info | using system latitude: 50.942911 longitude: 6.5644356
pvforecast.0 | 2023-02-15 14:16:47.790 | info | starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.pvforecast, node: v14.20.1, js-controller: 4.0.24
pvforecast.0 | 2023-02-15 14:16:41.898 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
pvforecast.0 | 2023-02-15 14:16:41.897 | info | terminating
pvforecast.0 | 2023-02-15 14:16:41.894 | info | Got terminate signal TERMINATE_YOURSELF
pvforecast.0 | 2023-02-15 14:15:05.072 | error | [updateActualWeatherData] failed to update weather data: TypeError: data.filter is not a function
pvforecast.0 | 2023-02-15 14:14:01.327 | info | Starting update cron (every 15 Minutes) for timezone: Europe/Berlin

</body>
</html>`

**Comment by klein0r** [comment]
You need a professional account for weather data

**Comment by klein0r** [comment]
> Maybe there should be a better error message.

Yes, the error shouldn't occur, thats why I haven't closed the issue.
